----
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: zalando-postgres
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: 1.14.0
  url: ssh://git@github.com:zalando/postgres-operator.git

----
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: zaland-postgres
  targetNamespace: default
  timeout: 3m0s
  wait: true