---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: zalando-postgres
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: v1.14.0
  url: https://github.com/zalando/postgres-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: zalando-postgres
  targetNamespace: default
  timeout: 3m0s
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-operator-ui
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./ui/manifests
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: zalando-postgres
  targetNamespace: default
  timeout: 3m0s
  wait: true