---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: prometheus-operator
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: v1.14.0
  url: https://github.com/prometheus-operator/prometheus-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: '.'
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: prometheus-operator
  targetNamespace: default
  timeout: 3m0s
  wait: true
