---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: v0.14.0
  url: https://github.com/prometheus-operator/kube-prometheus.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prom-stack
  namespace: flux-system
spec:
  interval: 10m0s
  path: '.'
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: kube-prometheus
  timeout: 3m0s
  wait: true
