apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
    team: trung
  name: trung
  namespace: default
spec:
  allowedSourceRanges: []
  databases:
    trung: trung
  enableConnectionPooler: true
  enableMasterPoolerLoadBalancer: true
  maintenanceWindows: []
  numberOfInstances: 3
  postgresql:
    version: '17'
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  teamId: acid
  users:
    trung: []
  volume:
    iops: 3000
    size: 10Gi
    throughput: 125
